ex14/music/history/urls.py
from django.urls import path

from . import views

app_name = "history"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    path('newArtist', views.newArtist, name='newArtist')
]

ex14/music/music/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('history/', include('history.urls')),
    path('admin/', admin.site.urls),
]

ex14/music/history/models.py
from django.db import models

# Create your models here.
class Artist(models.Model):
  artist_name = models.CharField(max_length=50)

  def __str__(self):
      return self.artist_name

class Song(models.Model):
  artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
  title = models.CharField(max_length=50)

  def __str__(self):
    return self.title

ex14/music/history/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Artist, Song

from .models import Artist
from .models import Song


def index(request):
    artist_list = Artist.objects.all()
    context = { "artist_list": artist_list }
    return render(request, 'history/index.html', context)


def detail(request, id):
    song_list = Song.objects.filter(artist_id = id)
    artist = Artist.objects.get(pk=id)
    context = { "song_list": song_list, "artist": artist }
    return render(request, "history/detail.html", context)


def newArtist(request):

  artist = Artist(artist_name = request.POST['artist'])
  artist.save()
  added_artist = Artist.objects.filter(artist_name = request.POST['artist'])
  return HttpResponseRedirect(reverse('history:detail', args=(added_artist[0].id,)))

ex14/music/history/templates/history/detail.html
<h1>{{ artist.artist_name }}'s song list</h1>
{% if song_list %}
<ul>
  {% for song in song_list %}
  <li>{{ song.title }}</li>
  {% endfor %}
{% else %}
  <p>No Songs</p>

</ul>
{% endif %}

ex14/music/history/templates/history/index.html
<h1>Artists</h1>

<ul>
  {% for artist in artist_list %}
  <li><a href="/history/{{ artist.id }}/"> {{ artist.artist_name }}</a></li>
  {% endfor %}
</ul>
<form method="post" action="{% url 'history:newArtist' %}">
    {% csrf_token %}
    <label for="newArtist">New Artist</label><br>
    <input type="text" name="artist" id = "newArtist">
    <input type = "submit" value="Artist">
  </form>