nss/nss/cohorts/urls.py
from django.urls import path
from . import views


app_name = 'cohorts'
urlpatterns = [
  # ex: /cohorts/
  path('', views.index, name='index'),
  # ex: /cohorts/5/
  path('<int:cohort_id>/', views.detail, name='detail')
]

nss/nss/nss/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cohorts/', include('cohorts.urls')),
]

nss/nss/cohorts/models.py
from django.db import models

# Create your models here.
class Cohort(models.Model):
  name = models.CharField(max_length=20)

  def __str__(self):
    return self.name

class Student(models.Model):
  name = models.CharField(max_length=120)
  fav_color = models.CharField(max_length=120)
  cohort = models.ForeignKey(Cohort, on_delete=models.CASCADE)

  def __str__(self):
    return self.name

nss/nss/cohorts/views.py
from django.shortcuts import render, get_object_or_404

from .models import Cohort, Student

# Create your views here.
def index(request):
  cohort_list = Cohort.objects.all()
  context = { 'cohort_list' : cohort_list }
  return render(request, 'cohorts/index.html', context)

def detail(request, cohort_id):
  cohort = get_object_or_404(Cohort, pk=cohort_id)
  student_list = Student.objects.filter(cohort_id=cohort_id)
  context = { 'cohort': cohort, 'student_list': student_list}
  return render(request, 'cohorts/detail.html', context)

nss/nss/cohorts/templates/cohorts/detail.html
<h1>Students in {{ cohort.name }}</h1>

<ul>
  {% for student in student_list %}
    <li>{{ student.name }}'s favortie color is {{ student.fav_color }}</li>
    {% endfor %}
</ul>

nss/nss/cohorts/templates/cohorts/index.html
<h1>All Cohorts</h1>

<ul>
  {% for cohort in cohort_list %}
  <!-- url finds the app 'cohorts and then finds the name of the route called 'detail'.  the route also expects a number so we give it cohort.id.   (localhost:8000/cohorts/2)-->
  <li><a href="{% url 'cohorts:detail' cohort.id %}">{{ cohort.name }}</a></li>
  {% endfor %}
</ul>